Remove source file if identical to target, allowing making of symlink.

diff --git a/gisym b/gisym
--- a/gisym
+++ b/gisym
@@ -16,16 +16,21 @@ check-symlink() {
 
     if [[ "$CURRENT_TARGET" != "$TARGET" ]]; then
         if [[ -e $SOURCE && ! -L $SOURCE ]]; then
-            echo "ERROR: File $SOURCE should be a symlink pointing to $TARGET but it already exists and is not a symlink, cannot proceed - please check."
-            exit 1
-        else
-            echo "WARNING! Symlink $SOURCE does not exist or does not point to $TARGET, making link."
-            rm -fv "$SOURCE"
-            ONE_DIRNAME=$(dirname "$SOURCE")
-            RELATIVE_TARGET=$(realpath --relative-to="$ONE_DIRNAME" "$TARGET")
-            mkdir -pv "$ONE_DIRNAME"
-            (cd "$ONE_DIRNAME" && ln -sv "$RELATIVE_TARGET" "$SOURCE")
+            if [[ -f "$SOURCE" ]] && cmp "$SOURCE" "$TARGET"; then
+                echo "WARNING! Source file $SOURCE is identical to $TARGET; removing $SOURCE."
+                rm "$SOURCE"
+            else
+                echo "ERROR: File $SOURCE should be a symlink pointing to $TARGET but it already exists and is not a symlink, cannot proceed - please check."
+                exit 1
+            fi
         fi
+
+        echo "Symlink $SOURCE does not exist or does not point to $TARGET, making link."
+        rm -fv "$SOURCE"
+        ONE_DIRNAME=$(dirname "$SOURCE")
+        RELATIVE_TARGET=$(realpath --relative-to="$ONE_DIRNAME" "$TARGET")
+        mkdir -pv "$ONE_DIRNAME"
+        (cd "$ONE_DIRNAME" && ln -sv "$RELATIVE_TARGET" "$SOURCE")
     fi
 }
 
